# Generated by Django 3.0.9 on 2021-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210117_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-date',), 'verbose_name': 'مشروع ', 'verbose_name_plural': 'المشاريع/Portfolio'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
