# Generated by Django 3.0.9 on 2021-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210117_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('sub', models.CharField(max_length=100, verbose_name='الموضوع')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('message', models.TextField(verbose_name='الموضوع')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رساله/طلب',
                'verbose_name_plural': 'الرسائل/الطلبات',
                'ordering': ('-date',),
            },
        ),
    ]
